# Generated by Django 5.1.1 on 2024-09-17 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_address_jobapplication'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobapplication',
            name='how_heard_about_us',
            field=models.CharField(choices=[('linkedin', 'LinkedIn'), ('instagram', 'Instagram'), ('social_media', 'Social Media'), ('other', 'Other')], max_length=50),
        ),
        migrations.AlterField(
            model_name='jobapplication',
            name='position_applied',
            field=models.CharField(choices=[('python', 'Python Developer'), ('java', 'Java Developer'), ('testing', 'Testing Engineer')], max_length=50),
        ),
    ]
