# Generated by Django 5.1.1 on 2024-09-17 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_alter_jobapplication_how_heard_about_us_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobapplication',
            name='birth_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
