# Generated by Django 5.1.1 on 2024-09-18 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0007_alter_jobapplication_birth_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobapplication',
            name='candidate_type',
            field=models.CharField(choices=[('Experience', 'Experienced'), ('Fresher', 'Fresher')], max_length=10, null=True),
        ),
    ]
