# Generated by Django 5.1.1 on 2024-09-18 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0008_jobapplication_candidate_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobapplication',
            name='available_start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
