# Generated by Django 5.1.1 on 2024-09-18 10:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0009_alter_jobapplication_available_start_date'),
    ]

    operations = [
        migrations.DeleteModel(
            name='JobApplication',
        ),
    ]
