# Generated by Django 5.1.1 on 2024-09-20 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0013_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobapplication',
            name='earliest_possible_start_date',
            field=models.DateField(null=True),
        ),
    ]
