# Generated by Django 5.1.1 on 2024-09-20 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0014_alter_jobapplication_earliest_possible_start_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobapplication',
            name='email_address',
            field=models.EmailField(max_length=254),
        ),
    ]
