# Generated by Django 5.1.1 on 2024-09-20 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0016_alter_jobapplication_email_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobapplication',
            name='first_name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
