# Generated by Django 5.1.1 on 2024-09-20 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0017_alter_jobapplication_first_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobapplication',
            name='first_name',
            field=models.CharField(max_length=255),
        ),
    ]
