# Generated by Django 5.1.1 on 2024-09-20 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0018_alter_jobapplication_first_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobapplication',
            name='email_address',
            field=models.EmailField(max_length=254),
        ),
    ]
