# Generated by Django 5.1.1 on 2024-09-26 11:20

import django.core.validators
import re
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0023_alter_jobapplication_email_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=255, validators=[django.core.validators.RegexValidator(re.compile('^(?=.*[a-zA-Z])(?=.*[0-9])(?=.*[!@#$%^&*()_+=-{};:"<>,./?]).{8,}$'), 'Password should be at least 8 characters, and contain at least one letter, one number, and one special character', 'invalid')]),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=255, unique=True, validators=[django.core.validators.RegexValidator(re.compile('^[a-zA-Z]+$'), 'Enter a valid username', 'invalid')]),
        ),
    ]
