# Generated by Django 5.1.1 on 2024-09-26 11:44

import website.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0024_alter_user_password_alter_user_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userregistration',
            name='confirm_password',
            field=models.CharField(max_length=128, validators=[website.models.validate_password]),
        ),
        migrations.AlterField(
            model_name='userregistration',
            name='first_name',
            field=models.CharField(max_length=50, validators=[website.models.validate_name]),
        ),
        migrations.AlterField(
            model_name='userregistration',
            name='last_name',
            field=models.CharField(max_length=50, validators=[website.models.validate_name]),
        ),
        migrations.AlterField(
            model_name='userregistration',
            name='password',
            field=models.CharField(max_length=128, validators=[website.models.validate_password]),
        ),
    ]
